'use strict';
console.log('hello, world');
const $heading = document.querySelector('h1');
console.log('$heading is ', $heading);
console.dir($heading);
const $explanation = document.querySelector('#explanation');
console.log('$explanation is ', $explanation);
console.dir($explanation);
const $hint = document.querySelector('.hint');
console.log('$hint is ', $hint);
console.dir($hint);
const $paragraph = document.querySelectorAll('p');
console.log('$paragraph is ', $paragraph);
const $links = document.querySelectorAll('.example-link');
console.log('$links is ', $links);
