'use strict';
const fullName = 'Erin Corcoran';
console.log('value of fullName: ', fullName);
const isCool = true;
console.log('value of isCool: ', isCool);
const totalPets = 1;
console.log('value of totalPets: ', totalPets);
console.log('typeof fullName: ', typeof fullName);
console.log('typeof isCool: ', typeof isCool);
console.log('typeof totalPets: ', typeof totalPets);
const empty = null;
console.log('value of empty: ', empty);
console.log('typeof empty: ', typeof empty);
let nothing;
console.log('value of nothing: ', nothing);
console.log('typeof nothing: ', typeof nothing);
