'use strict';
const width = 10;
const height = 2;
const area = width * height;
console.log('value of area:', area);
console.log('type of area:', typeof area);
const bill = 99.5;
const payment = 100;
const change = payment - bill;
console.log('value of change:', change);
console.log('type of change:', typeof change);
const quizzes = 90;
const midterm = 82;
const final = 92;
const grade = (quizzes + midterm + final) / 3;
console.log('value of grade:', grade);
console.log('type of grade:', typeof grade);
const firstName = 'Erin';
const lastName = 'Corcoran';
const fullName = firstName + ' ' + lastName;
console.log('value of fullName:', fullName);
console.log('type of fullName:', typeof fullName);
const pH = 10;
const isAcidic = pH < 7;
console.log('value of isAcidic:', isAcidic);
console.log('type of isAcidic:', typeof isAcidic);
const headCount = 250;
const isSparta = headCount === 300;
console.log('value of isSparta:', isSparta);
console.log('type of isSparta:', typeof isSparta);
let motto = fullName;
motto += ' is the GOAT';
console.log('value of motto:', motto);
console.log('type of motto:', typeof motto);
